### ISSUE TITLE
Incompatibility with tasty-1.4

### ISSUE THREAD

**Issue by Minoru** [nomeata/tasty-expected-failure#24]
Hi! I'm using tasty-expected-failure to check that my code calls `error` in some cases. This worked great so far, but after an update to tasty-1.4, the exceptions generated by `error` are *not* caught, and instead propagate to tasty which then fails the test.

<details>
<summary>Minimal, reproducible example</summary>

_reproducer.cabal_
```
cabal-version:       1.12

name:                reproducer
version:             0.1.0.0
license-file:        LICENSE
author:              Alexander Batischev
maintainer:          eual.jp@gmail.com
build-type:          Simple

library
  exposed-modules:     MyLib
  build-depends:       base >=4.13 && <5
  default-language:    Haskell2010

test-suite reproducer-test
  default-language:    Haskell2010
  type:                exitcode-stdio-1.0
  main-is:             MyLibTest.hs
  build-depends:       base >=4.13 && <5,
                       reproducer,
                       tasty,
                       tasty-hunit ==0.10.0.3,
                       tasty-expected-failure ==0.12.1
```

_MyLib.hs_

```haskell
module MyLib (MyResultType(..), someFunc) where

data MyResultType = MyResultType
  { mrtOne :: String,
    mrtTwo :: String
  }
  deriving (Eq, Show)

someFunc :: String -> MyResultType
someFunc fp =
  MyResultType
    -- Fails.
    { mrtOne = fp,
      mrtTwo = undefined
    }

    -- Curiously, reordering the lines makes it work as expected.
    {-
    { mrtOne = undefined,
      mrtTwo = fp
    }
    -}
```

_MyLibTest.hs_

```haskell
import MyLib
import Test.Tasty (defaultMain, TestTree)
import Test.Tasty.ExpectedFailure (expectFail)
import Test.Tasty.HUnit

main :: IO ()
main = defaultMain myTest

output :: MyResultType
output =
  MyResultType
    { mrtOne = "",
      mrtTwo = ""
    }

myTest :: TestTree
myTest =
  expectFail $
    testCase
      "this is expected to fail"
      (someFunc "Hello, world!" @?= output)
```

</details>

With tasty 1.3.1, I get the expected result — the exception thrown by `undefined` gets caught by tasty-expected-failure, resulting in "FAIL (expected)" message:

```
$ cabal test --enable-tests --constrain 'tasty == 1.3.1'
[…]

$ cat dist-newstyle/…/reproducer-0.1.0.0-reproducer-test.log
Test suite reproducer-test: RUNNING...
this is expected to fail: FAIL (expected)
  message threw an exception: Prelude.undefined
  CallStack (from HasCallStack):
    error, called at libraries/base/GHC/Err.hs:80:14 in base:GHC.Err
    undefined, called at ./MyLib.hs:14:16 in main:MyLib

All 1 tests passed (0.00s)
Test suite reproducer-test: PASS
```

With tasty 1.4.0.1, I get a "FAIL" message instead:

```
$ cabal test --enable-tests --constrain 'tasty == 1.4.0.1'
[…]
Test suite reproducer-test: RUNNING...
this is expected to fail: FAIL
  Exception: Prelude.undefined
  CallStack (from HasCallStack):
    error, called at libraries/base/GHC/Err.hs:80:14 in base:GHC.Err
    undefined, called at ./MyLib.hs:14:16 in main:MyLib

1 out of 1 tests failed (0.00s)
Test suite reproducer-test: FAIL
```

I narrowed it down to https://github.com/feuerbach/tasty/commit/fcfccc8ea991583d649f5129b83660d6cee38d8b. If I manually use that commit's parent, everything works as expected (the first listing above):

_cabal.project_
```yaml
packages: .

source-repository-package
    type: git
    location: https://github.com/feuerbach/tasty
    tag: 96795203335a54d39e3587c890c2879a3c1a0150
    subdir: core
```

If I specify `tag: fcfccc8ea991583d649f5129b83660d6cee38d8b` instead, I get the unexpected behaviour (second listing above).

Looking at the offending commit, I don't see how it could cause this regression. If anything, it should force exceptions to be thrown *sooner*, enabling tasty-expected-failure to catch more of them — but the situation is exactly the opposite now.

tasty-1.4 have been out for a month now, tasty-expected-result got downloaded 245 times in the last 30 days, and no-one reported this yet, so I'm assuming my code is broken somehow?

I'm at my wits' end here. Does anyone have any idea as to what's going on and how to fix it?

**Comment by nomeata** [comment]
I lost track of the things related to exceptions and `expected-failure`.  @kquick is the most recent expert, maybe he can advise?

@Minoru , did you see #21 – maybe that applies to you as well?

**Comment by Minoru** [comment]
This appears to be a different issue. I changed the "timeout offset" to 100ms, and my reproducer still misbehaves as described above. Hoping @kquick has some more insight into this.

**Comment by kquick** [comment]
You are correct, this is not issue #21.

Thank you for the minimal reproduction and for tracking this down to a specific commit in tasty!

The error you are encountering is actually a new behavior in `tasty` itself: it is trying  to force evaluation of the error report within the context of its timeout in case the `show` diverges (does not finish). If you implement this test in `tasty-hspec` without using `tasty-expected-failure`, the same `Exception: Prelude.undefined` message will be shown there.  The reason is that `tasty` is  trying to show the failure, which includes the values that caused the failure, but trying to `show` an `undefined` causes an exception.

The situation gets even more interesting at this point.  Looking at issue 280 in `tasty`, the issue was closed with commit `d5286ee`, which has protection for the situation where the failure reporting would throw an exception (which would have avoided this issue 24).  However a day later, the `fcfccc8` commit was made, which has the forcing but does not have the protections, and the `d5286ee` commit is reported as orphaned.  It's not clear why feuerbach decided to remove the protections in the final version.

[It's hard to actually add any checking for this to tasty itself... since all of its tests _must_ succeed. Too bad it can't expect failures to check them successfully. :-) ]

The normal operation for `tasty-expected-failure` is:
  *  if there is (unexpected!) success of the test, it shows "(unexpected success)" and increments the failed tests count
  * if the test fails, it uses tasty's normal failure result display  to show FAIL, the values involved, then notes that this is expected and the failed tests count is *not* incremented.

The problem here is that when the test fails (as expected!) the value is shown, and if the `show` operation throws an exception (e.g. by trying to `show` an `undefined`) the old `tasty` would show `Exception: Prelude.undefined`, but it would do that *after* checking the test results, so the failure count is not incremented; in `tasty` `1.4` or later, the `show` is forced *after* the test itself (and after `tasty-expected-failure` says it's OK) but *before* the test post-processing completes, so the exception is not only shown but it increments the failure counter  down in `tasty` itself.

An interesting way to see this is to update your minimal failure with `tasty` `1.3` to add `testCase "oops" (3 @?= 4)` and run it with `tasty` `1.3` which will cause a failure and therefore the display: you will see the `Exception: Prelude.undefined` message now because there's another failing test that causes all test results to be shown.

The fix for this is a little byzantine.  Essentially the fix in #25  updates `tasty-expected-failure` to also force the display of the failure reason, which causes the `undefined` exception to occur within `tasty-expected-failure`.  The behavior I added for catching exceptions therefore catches this exception.. and reports back to tasty that it got an expected failure due to an exception.  This latter failure is reported *instead* of the original failure, but it doesn't cause a failure in `tasty`'s new post-processing because the text of the failure report is *not* an attempt to `show` the `undefined`, but instead the text of the exception generated by that attempt inside `tasty-expected-failure`.

Thus, `tasty-expected-failure` correctly reports that the test failed.  It reports the wrong reason for that failure, but since the value will only be attempted to be shown (causing the reported failure) if the underlying test actually failed, the outcome is consistent with the intent, even though it's mis-reported.  I could have modified the fix so that it indicated that both the original test failed *and* the `show` of the failure also failed, but I don't think it would have been much more helpful.

**Comment by nomeata** [comment]
Wow, thanks for that analysis and fix! I'm grateful for your help here!

**Comment by Minoru** [comment]
@kquick This is mind-blowing. Thank you very much for figuring it out! I verified and can confirm that #25 fixes the problem in my "real" test suite, not just the reproducer.

Out of curiosity: how did you track down the cause? Was it by [Feynman's algorithm](https://www.quora.com/What-do-you-think-of-Richard-Feynmans-problem-solving-algorithm-Write-down-the-problem-think-very-hard-write-down-the-answer?share=1), or is there some easier ways to do it? Did you just wrap tasty's internals in a `catch` block and then narrowed its scope to figure out where the exception comes from?

**Comment by kquick** [comment]
@Minoru: Ha, I wish I was in Feynman's class!  Your tracking down the specific tasty commit was the biggest clue, followed by some hunches and experimentation, and then a too-long period of confusion until I figured out that the `d5286ee` commit was not actually in the tasty 1.4 branch.  I'm glad this fixes your issues, and thanks again for the reproduction and initial research!

@nomeata: I'm glad to help!

**Comment by Minoru** [comment]
#25 fixed this issue, so I'm closing it. I also notice that the fix is already released as part of tasty-expected-failure 0.12.2 — awesome! Thank you both for the prompt fix and the release!

**Comment by Minoru** [comment]
@nomeata, by the way, this repo lacks 0.12.1 and 0.12.2 Git tags — did you forget to push them, or simply stopped tagging releases in Git history?

**Comment by nomeata** [comment]
Forgot to tag them; fixed.
